;;; Automatically generated by ‘recentf’ on Sat Apr  8 10:05:09 2023.

(setq recentf-list
      '(
        "~/.emacs.d/.gitignore"
        "~/.emacs.d/init.el"
        "~/.emacs.d/emacs-config.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
