;;; -*- coding: utf-8; mode: lisp-data -*-
(("c:/Users/xiudi/AppData/Roaming/.emacs.d/"
  (dired-filename . "c:/Users/xiudi/AppData/Roaming/.emacs.d/init.el"))
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/emacs-config.org" . 71978)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/txs/2023.bean" . 3070)
 ("c:/Users/xiudi/AppData/Roaming/org/notes/(MultiPath++) Efficient Information Fusion and Trajectory Aggregation for Behavior Prediction.org" . 266)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/accounts/Income.bean" . 138)
 ("d:/research/ADS/Report/MultiPath/_region_.tex" . 1077)
 ("d:/research/ADS/Report/MultiPath/slide.tex" . 446)
 ("d:/research/ADS/Report/MultiPath/pages/chapter2.tex" . 1203)
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/var/treemacs/persist.org" . 70)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/0019.chat" . 667)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/0020.chat" . 3435)
 ("c:/Users/xiudi/AppData/Roaming/org/diary.org" . 4687)
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/var/elfeed/db/index" . 630)
 ("c:/Users/xiudi/AppData/Roaming/org/phd.org" . 3452)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/main.bean" . 326)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/accounts/Expenses.bean" . 1335)
 ("c:/Users/xiudi/AppData/Roaming/org/habits.org" . 567)
 ("d:/aioWriting/notes/computer/recipe/Emacs/OrgMode/OrgMode.org" . 365)
 ("c:/Users/xiudi/AppData/Roaming/org/notes/Emacs/OrgMode/KnowledgeBase.org" . 553)
 ("d:/research/ADS/Literature/CVPR_simAgents/"
  (dired-filename . "d:/research/ADS/Literature/CVPR_simAgents/(ArXiv MultiPath++) Efficient Information Fusion and Trajectory Aggregation for Behavior Prediction.pdf"))
 ("c:/Users/xiudi/AppData/Roaming/org/recipe/breakfast.org" . 192)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/accounts/Assets.bean" . 357)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/README.org" . 187)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/accounts/Liabilities.bean" . 58)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/accounts/Equity.bean" . 87)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/txs/" . 113)
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/accounts/" . 118)
 ("e:/Emacs/"
  (dired-filename . "e:/Emacs/Uninstall.exe"))
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/lisp/"
  (dired-filename . "c:/Users/xiudi/AppData/Roaming/.emacs.d/lisp/cdlatex.el"))
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/lisp/beancount.el" . 44241)
 ("c:/Users/xiudi/AppData/Roaming/org/recipe/img/燕麦粥/"
  (dired-filename . "c:/Users/xiudi/AppData/Roaming/org/recipe/img/燕麦粥/2023-04-10_12-38-21_screenshot.png"))
 ("c:/Users/xiudi/AppData/Roaming/org/Beancount/" . 109)
 ("c:/Users/xiudi/AppData/Roaming/org/habits.org_archive" . 142)
 ("d:/research/LFRS/Literature/Masked Autoencoders Are Scalable Vision Learners.org" . 166)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/chat10.chat" . 5779)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/11.chat" . 4532)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/0011.chat" . 2787)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/0012.chat" . 2861)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/0013.chat" . 2732)
 ("c:/Users/xiudi/AppData/Roaming/org/20230403T132743--orgmode__emacs.org" . 112)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/0001.chat" . 6326)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/0002.chat" . 3916)
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/lisp/init-dev.el" . 2795)
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/lisp/init-completion.el" . 1348)
 ("c:/Users/xiudi/AppData/Roaming/org/chat/" . 204)
 ("d:/research/ADS/Literature/chatgpt/chat04.chat" . 4891)
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/init.el" . 1177)
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/all-the-icons/"
  (dired-filename . "c:/Users/xiudi/AppData/Roaming/.emacs.d/all-the-icons/NotoColorEmoji-Regular.ttf"))
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/eaf/"
  (dired-filename . "c:/Users/xiudi/AppData/Roaming/.emacs.d/eaf/browser"))
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/cnfonts/"
  (dired-filename . "c:/Users/xiudi/AppData/Roaming/.emacs.d/cnfonts/cnfonts.conf"))
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/early-init.el" . 989)
 ("c:/Users/xiudi/AppData/Roaming/.emacs.d/.gitignore" . 245)
 ("d:/research/ADS/Literature/chatgpt/" . 1197)
 ("d:/codes/python/hello.py" . 170))
