;;; -*- coding: utf-8; mode: lisp-data -*-
(("/home/mawen/.emacs.d/emacs-config.org" . 86469)
 ("/home/mawen/.emacs.d/mind-wave/mind_wave.py" . 982)
 ("/home/mawen/.zshrc" . 564)
 ("/home/mawen/.emacs.d/mind-wave/" . 546)
 ("/home/mawen/.emacs.d/var/treemacs/persist.org" . 73)
 ("/home/mawen/aioWriting/notes/computer/recipe/Emacs/LaTeX/LaTeX.org" . 1330)
 ("/home/mawen/org/recipe/breakfast.org" . 1064)
 ("/home/mawen/org/Beancount/txs/2023.bean" . 1863)
 ("/home/mawen/.emacs.d/emacs-rime/" . 989)
 ("/home/mawen/Documents/(MultiPath++) Efficient Information Fusion and Trajectory Aggregation for Behavior Prediction.org" . 224)
 ("/home/mawen/.emacs.d/elpa/pdf-tools-20230322.1541/pdf-tools-autoloads.el" . 20678)
 ("/home/mawen/.emacs.d/elpa/tablist-20230321.705/tablist-autoloads.el" . 1352)
 ("/home/mawen/.emacs.d/elpa/markdown-mode-20230326.954/markdown-mode-autoloads.el" . 1689))
